### ISSUE TITLE
Fails for POST requests

### ISSUE THREAD

**Issue by markuspalme** [markuspalme/Security.HmacAuthentication#1]
See https://github.com/ademcaglin/Security.HmacAuthentication/issues/1#issuecomment-466450328 for details.

**Comment by markuspalme** [comment]
@PerryD: 
I tested a POST request with a JSON body and it works for me. To reproduce, please provide some more details on your setup and scenario.

I also suggest to create a breakpoint in `HmacAuthenticationHandler` in line 112 to verify which part of the signature does not match.

**Comment by PerryD** [comment]
@markuspalme , Thanks. Some followup. I cloned your project and wrote a post request test. Much like the other solution I tried, the authentication step in the POST request actually succeeds. It is what happens after the authn that is the issue.

I am securing a .Net Core web api. On my controller, if I have no authn, both get requests and post requests work fine. When I turn on authentication, the GET request still authenticates and returns a valid response with data. The POST request passes authn, but then returns a 400 Bad Request.

In all fairness, what you have seems to work as far as the authn is concerned. Just can't figure out why the POST request ultimately fails even after authn succeeds.

**Comment by markuspalme** [comment]
@PerryD: I tested this scenario and it works with this implementation. It does indeed NOT work with the orignal implementation this fork is based on because it does not rewind the body buffer after reading the request. Did you use the code from this repository? I'm asking because you opened the initial issue in another repo.

**Comment by PerryD** [comment]
@markuspalme . Thanks, ya, sorry about the confusion. I actually did use your implementation, and as you found out, authn does work with the POST request.

The issue is when I turn on authentication on my api.

`return Task.FromResult(AuthenticateResult.Success(ticket));`

I can debug and see that the step above is hit successfully in HandleAuthenticateAsync, and then I get a 400 Bad Request in my client. I think I have  config issue in my client or api somewhere that I need to hunt down.

I think you can safely assume this is not an issue with your implementation. Thanks.

**Comment by markuspalme** [comment]
Feel free to post an example of a not working scenarion and I will take a look.

**Comment by PerryD** [comment]
https://github.com/PerryD/UserManagementApi

@markuspalme, couple of points here:

1. This doesn't look exactly like your solution. I took what you provided and worked it into my test solution. So feel free to ignore all this if you would like. No obligation. :)
2. As I mentioned before, the authentication as you provided works for GET and POST. So this really isn't about whether the authn is working. It is.
3. The failure comes in AFTER authentication passes, and before the response is returned. So we actually get to line 45 in HmacAuthenticationHandler, but then get a 400 Bad Request back.

So if you comment out line 9 in the UserController, the test pass.
If you leave line 9 in there, only the GET returns 200. POST returns 400.

Maybe I am going about it wrong which could be the case.

**Comment by PerryD** [comment]
@markuspalme, you can close this. I got it working. Not actually sure what the issue was as I didn't change much, just moved some things around and refactored a little. Anyways, thanks for providing this solution and thanks for your help.

**Comment by markuspalme** [comment]
@PerryD  Thanks for your feedback, I will close the issue.
